# Generated by Django 2.1.7 on 2019-02-14 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0006_auto_20190212_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='responsible',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='contributors',
        ),
        migrations.AddField(
            model_name='todo',
            name='contributors',
            field=models.ManyToManyField(default=None, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
