# Generated by Django 2.2.4 on 2019-08-13 02:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_auto_20190222_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contributors',
            field=models.ManyToManyField(default=None, null=True, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
