# Generated by Django 2.2.4 on 2019-08-16 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_auto_20190815_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contributors',
            field=models.ManyToManyField(blank=True, default=[], related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
    ]
